---
name: "(chunk) Create release"

on:
  workflow_call:
    inputs:
      library_version:
        type: string
        required: true
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@4edd7a5aabb1bc62e6dc99b3302d587bf3134e20"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          automatic_release_tag: "v${{ inputs.library_version }}"
