---
name: "(chunk) Create release"

on:
  workflow_call:
    inputs:
      library_version:
        type: string
        required: true
    secrets:
      REPOSITORY_TOKEN:
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@4edd7a5aabb1bc62e6dc99b3302d587bf3134e20"
        with:
          repo_token: ${{ secrets.REPOSITORY_TOKEN }}
          draft: true
          automatic_release_tag: ${{ inputs.library_version }}
