---
name: "(chunk) Parse version"

on:
  workflow_call:
    inputs:
      github_sha:
        type: string
        required: false
        default: master
    outputs:
      LIBRARY_VERSION:
        description: "Version of the library"
        value: ${{ jobs.get_library_version.outputs.LIBRARY_VERSION }}

jobs:
  get_library_version:
    runs-on: ubuntu-latest
    outputs:
      LIBRARY_VERSION: ${{ steps.tag_name.outputs.LIBRARY_VERSION }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.github_sha }}
      - name: Get version from CMakeLists.txt
        id: tag_name
        run: |
          LIBRARY_VERSION=$(sed -ne 's/^.*[^0-9]VERSION \([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/p' CMakeLists.txt)
          echo ::set-output name=LIBRARY_VERSION::${LIBRARY_VERSION}
      - name: Check the tag
        env:
          LIBRARY_VERSION: ${{ steps.tag_name.outputs.LIBRARY_VERSION }}
        run: |
          echo $LIBRARY_VERSION
