---
name: "Build and tests"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cmakelists-version:
    uses: jgsogo/template-cpp-project/.github/chunks/_parse_version.yml@master
    with:
      github_sha: ${{ github.sha }}

  ci:
    uses: jgsogo/template-cpp-project/.github/chunks/_build.yml@master
    with:
      library_name: composite
      library_version: ${{ needs.cmakelists-version.outputs.LIBRARY_VERSION }}
      github_sha: ${{ github.sha }}
