---
name: "Build and tests"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cmakelists-version:
    uses: jgsogo/template-cpp-project/.github/workflows/_parse_version.yml@master
    with:
      github_sha: ${{ github.sha }}

  ci:
    needs:
      cmakelists-version
    uses: jgsogo/template-cpp-project/.github/workflows/_build.yml@master
    with:
      library_name: ${{ github.event.repository.name }}
      library_version: ${{ needs.cmakelists-version.outputs.LIBRARY_VERSION }}
      github_sha: ${{ github.sha }}
