---
name: "(Manual) Create new tag and release"

on: workflow_dispatch

jobs:
  cmakelists-version:
    uses: jgsogo/template-cpp-project/.github/workflows/_parse_version.yml@master
    with:
      github_sha: master

  release-available:
    needs:
      cmakelists-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --tags
          git tag | tail -1
          LATEST_TAG=$(git tag | tail -1)
          if [ "${LATEST_TAG}" = "v${{ needs.cmakelists-version.outputs.LIBRARY_VERSION }}" ] ; then
            echo "Release ${LATEST_TAG} already exists!"
            exit 1
          fi

  ci-cpp20:
    uses: jgsogo/template-cpp-project/.github/workflows/_build.yml@master
    needs:
      - release-available  # Only run tests if version is available
      - cmakelists-version  # Needed to access dependent variable
    with:
      library_name: ${{ github.event.repository.name }}
      library_version: ${{ needs.cmakelists-version.outputs.LIBRARY_VERSION }}
      github_sha: master
      profile: cpp20

  ci-default:
    uses: jgsogo/template-cpp-project/.github/workflows/_build.yml@master
    needs:
      - release-available  # Only run tests if version is available
      - cmakelists-version  # Needed to access dependent variable
    with:
      library_name: ${{ github.event.repository.name }}
      library_version: ${{ needs.cmakelists-version.outputs.LIBRARY_VERSION }}
      github_sha: master
      profile: default

  create_release:
    uses: jgsogo/template-cpp-project/.github/workflows/_create_release.yml@master
    needs:
      - ci-default
      - ci-cpp20
      - cmakelists-version  # Needed to access dependent variable
    with:
      library_version: v${{ needs.cmakelists-version.outputs.LIBRARY_VERSION }}
    secrets:
      REPOSITORY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
