---
name: "(Manual) Update lockfile"

on: 
  workflow_dispatch:
  schedule:
    # Trigger every sunday at 9:00
    - cron: "0 9 * * 0"

env:
  CONAN_USER_HOME: /home/conan

defaults:
  run:
    working-directory: /home/conan/library

jobs:
  cmakelists-version:
    uses: jgsogo/template-cpp-project/.github/workflows/_parse_version.yml@master
    with:
      github_sha: master

  update_lockfile:
    needs:
      cmakelists-version
    uses: jgsogo/template-cpp-project/.github/workflows/_update_lockfile.yml@master
    with:
      docker_image: conanio/gcc11-ubuntu16.04:1.47.0
      library_name: ${{ github.event.repository.name }}
      library_version: ${{ needs.cmakelists-version.outputs.LIBRARY_VERSION }}
      profile: cpp20
    secrets:
      APP_RECIPES_APP_ID: ${{ secrets.APP_RECIPES_APP_ID }}
      APP_RECIPES_PRIVATE_KEY: ${{ secrets.APP_RECIPES_PRIVATE_KEY }}
